### ISSUE TITLE
Problems encountered in generating synthesized data

### ISSUE THREAD

**Issue by EWE002** [MiraPurkrabek/RePoGen#11]
Thanks for such an innovative work!
I have some questions about the process of creating my own synthesized data, when I run the
python scripts/sample_random_poses.py
In sample_random_poses.py, smplx_MALE_indices.npz is needed, which is obtained from obj_to_indices.py in tools, but obj_to_indices.py needs a file called verts_generated.npz in obj_to_indices.py.
What is vertices_generated.npz? Where can I get it?

**Comment by EWE002** [comment]
I have tried to put the textures folder in the root directory myself, as follows
/RePoGen/textures/blur/images/blur_0.jpg
But then the following error occurs:
Generating poses and views...
  0%| | 0/2 [00:00<? , ?it/s]
Traceback (most recent call last).
  File "scripts/sample_random_poses.py", line 767, in <module>
    main(args)
  File "scripts/sample_random_poses.py", line 304, in main
    tri_mesh = get_textured_mesh(vertices, texture_path=None, args=args)
  File "scripts/sample_random_poses.py", line 143, in get_textured_mesh
    m = trimesh.load(obj_path)
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/trimesh/exchange/load.py", line 114, in load
    ) = parse_file_args(file_obj=file_obj, file_type=file_type, resolver=resolver)
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/trimesh/exchange/load.py", line 605, in parse_file_args
    raise ValueError(f "string is not a file: {file_obj}")
ValueError: string is not a file: textures/glass/mappings/smplx_UV.obj
I know smplx_UV.obj is going to https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=smplx_uv.zip, but where should I put the downloaded file?

**Comment by MiraPurkrabek** [comment]
Hi @EWE002 ,

I did not generate the *SMPL_MALE_indices.npz* file through the *obj_to_indices.py* script but downloaded it from other project. I can't find referene to the project now so I'm uploading the required npz file instead.
If you find other way to get this mapping, please let me know.

The file is available here:
https://drive.google.com/file/d/13osjQAbgCJD4hgDr3BUAyC40r2QfV8-P/view?usp=sharing

**Comment by EWE002** [comment]
Hi @MiraPurkrabek , 
Thank you very much for your answer, 
but after solving the above problem I have encountered a new problem, which is as follows.
Generating poses and views...
  0%|                                                                                                                                       | 0/2 [00:00<?, ?it/s]DRI3 not available
failed to load driver: zink
  0%|                                                                                                                                       | 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "scripts/sample_random_poses.py", line 785, in <module>
    main(args)
  File "scripts/sample_random_poses.py", line 388, in main
    visibilities = msh.vertex_visibility(
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/psbody/mesh/mesh.py", line 284, in vertex_visibility
    vis, n_dot_cam = self.vertex_visibility_and_normals(camera, omni_directional_camera)
  File "/home/m11002163/.conda/envs/mesh/lib/python3.8/site-packages/psbody/mesh/mesh.py", line 295, in vertex_visibility_and_normals
    'cams': np.array([camera.origin.flatten()])}
AttributeError: 'list' object has no attribute 'origin'
This looks like a problem in the mesh?
About the mesh installation, I am following https://github.com/MPI-IS/mesh/tree/master
After I run the test on that page, it shows no problem.
What could be the problem?
Thank you in advance.

**Comment by MiraPurkrabek** [comment]
Hello @EWE002 

I'm looking into in now. Since it is not related to the original problem, I created a new issue #12 and closing this one as completed.
