### ISSUE TITLE
How do I trigger inference? 

### ISSUE THREAD

**Issue by SkalskiP** [MiraPurkrabek/RePoGen#3]
Hi @MiraPurkrabek 👋🏻

Awesome project. I plan to integrate it into my Computer Vision in Sports [repository](https://github.com/SkalskiP/sport). Could you provide me with some instructions on how to run the inference?

**Comment by MiraPurkrabek** [comment]
Hello @SkalskiP ,

Thank you for your interest in our work.
Do you have a problem with something specific? The code installation is straightforward (a simple pip command) and is described in the README. Then you have to register on the SMPL-X website (license requirement) and download their models. The instruction they give is well writen and should be easy to follow. Link is again in the README.

Let me know if you have any questions.

**Comment by MiraPurkrabek** [comment]
Closing the issue as there is no further discussion. Please feel free to re-open it if you need to.
